/**
 * @typedef {Object} Task
 * @property {string} id - UUID v4 generated by crypto.randomUUID()
 * @property {string} title - The task title text
 * @property {boolean} isCompleted - Whether the task has been completed
 */

/**
 * Creates a new Task object with a generated ID and default values.
 * @param {string} title
 * @returns {Task}
 */
export function createTask(title) {
  return {
    id: crypto.randomUUID(),
    title,
    isCompleted: false,
  };
}
